// AzLingo v3 data
const AZ_DATA = {
  "levels": [
    "A1",
    "A2",
    "B1",
    "B2",
    "C1"
  ],
  "words": {
  "A1": [
  { "en": "the", "uz": "(artikl)" },
  { "en": "be", "uz": "bo‘lmoq" },
  { "en": "to", "uz": "ga / uchun" },
  { "en": "of", "uz": "ning" },
  { "en": "and", "uz": "va" },
  { "en": "a", "uz": "(bir, artikl)" },
  { "en": "in", "uz": "ichida" },
  { "en": "that", "uz": "u / ki" },
  { "en": "have", "uz": "ega bo‘lmoq" },
  { "en": "I", "uz": "men" },
  { "en": "it", "uz": "u (narsa, hayvon)" },
  { "en": "for", "uz": "uchun" },
  { "en": "not", "uz": "emas" },
  { "en": "on", "uz": "ustida" },
  { "en": "with", "uz": "bilan" },
  { "en": "he", "uz": "u (erkak)" },
  { "en": "she", "uz": "u (ayol)" },
  { "en": "you", "uz": "sen / siz" },
  { "en": "we", "uz": "biz" },
  { "en": "they", "uz": "ular" },
  { "en": "do", "uz": "qilmoq" },
  { "en": "say", "uz": "aytmoq" },
  { "en": "go", "uz": "bormoq" },
  { "en": "can", "uz": "qila olmoq" },
  { "en": "see", "uz": "ko‘rmoq" },
  { "en": "get", "uz": "olmoq" },
  { "en": "make", "uz": "yasamoq / qilmoq" },
  { "en": "know", "uz": "bilmoq" },
  { "en": "think", "uz": "o‘ylamoq" },
  { "en": "want", "uz": "xohlamoq" },
  { "en": "need", "uz": "kerak bo‘lmoq" },
  { "en": "like", "uz": "yoqtirmoq" },
  { "en": "come", "uz": "kelmoq" },
  { "en": "use", "uz": "foydalanmoq" },
  { "en": "work", "uz": "ishlamoq" },
  { "en": "ask", "uz": "so‘ramoq" },
  { "en": "help", "uz": "yordam bermoq" },
  { "en": "give", "uz": "bermoq" },
  { "en": "look", "uz": "qaramoq" },
  { "en": "find", "uz": "topmoq" },
  { "en": "call", "uz": "qo‘ng‘iroq qilmoq" },
  { "en": "try", "uz": "urinmoq" },
  { "en": "open", "uz": "ochmoq" },
  { "en": "close", "uz": "yopmoq" },
  { "en": "live", "uz": "yashamoq" },
  { "en": "eat", "uz": "yemoq" },
  { "en": "drink", "uz": "ichmoq" },
  { "en": "sleep", "uz": "uxlamoq" },
  { "en": "sit", "uz": "o‘tirmoq" },
  { "en": "stand", "uz": "turmoq" },
  { "en": "walk", "uz": "yurmoq" },
  { "en": "run", "uz": "yugurmoq" },
  { "en": "read", "uz": "o‘qimoq" },
  { "en": "write", "uz": "yozmoq" },
  { "en": "speak", "uz": "gapirmoq" },
  { "en": "listen", "uz": "tinglamoq" },
  { "en": "watch", "uz": "tomosha qilmoq" },
  { "en": "play", "uz": "o‘ynamoq" },
  { "en": "study", "uz": "o‘qimoq" },
  { "en": "learn", "uz": "o‘rganmoq" },
  { "en": "love", "uz": "sevmok" },
  { "en": "buy", "uz": "sotib olmoq" },
  { "en": "sell", "uz": "sotmoq" },
  { "en": "clean", "uz": "tozalamoq" },
  { "en": "start", "uz": "boshlamoq" },
  { "en": "stop", "uz": "to‘xtamoq" },
  { "en": "home", "uz": "uy" },
  { "en": "school", "uz": "maktab" },
  { "en": "teacher", "uz": "o‘qituvchi" },
  { "en": "student", "uz": "o‘quvchi / talaba" },
  { "en": "book", "uz": "kitob" },
  { "en": "pen", "uz": "ruchka" },
  { "en": "table", "uz": "stol" },
  { "en": "chair", "uz": "stul" },
  { "en": "car", "uz": "mashina" },
  { "en": "bus", "uz": "avtobus" },
  { "en": "train", "uz": "poyezd" },
  { "en": "plane", "uz": "samolyot" },
  { "en": "city", "uz": "shahar" },
  { "en": "country", "uz": "mamlakat" },
  { "en": "world", "uz": "dunyo" },
  { "en": "day", "uz": "kun" },
  { "en": "night", "uz": "tun" },
  { "en": "morning", "uz": "ertalab" },
  { "en": "evening", "uz": "kechqurun" },
  { "en": "year", "uz": "yil" },
  { "en": "time", "uz": "vaqt" },
  { "en": "family", "uz": "oila" },
  { "en": "friend", "uz": "do‘st" },
  { "en": "man", "uz": "erkak" },
  { "en": "woman", "uz": "ayol" },
  { "en": "child", "uz": "bola" },
  { "en": "people", "uz": "odamlar" },
  { "en": "water", "uz": "suv" },
  { "en": "food", "uz": "ovqat" },
  { "en": "house", "uz": "uy" },
  { "en": "street", "uz": "ko‘cha" },
  { "en": "shop", "uz": "do‘kon" },
  { "en": "computer", "uz": "kompyuter" },
  { "en": "phone", "uz": "telefon" },
  { "en": "music", "uz": "musiqa" },
  { "en": "movie", "uz": "film" },
  { "en": "happy", "uz": "baxtli" },
  { "en": "good", "uz": "yaxshi" },
  { "en": "bad", "uz": "yomon" },
  { "en": "big", "uz": "katta" },
  { "en": "small", "uz": "kichik" },
  { "en": "new", "uz": "yangi" },
  { "en": "old", "uz": "eski" },
  { "en": "hot", "uz": "issiq" },
  { "en": "cold", "uz": "sovuq" },
  { "en": "beautiful", "uz": "chiroyli" },
  { "en": "easy", "uz": "oson" },
  { "en": "hard", "uz": "qiyin" },
  { "en": "yes", "uz": "ha" },
  { "en": "no", "uz": "yo‘q" },
  { "en": "please", "uz": "iltimos" },
  { "en": "thanks", "uz": "rahmat" },
  { "en": "sorry", "uz": "uzr" },
  { "en": "hello", "uz": "salom" },
  { "en": "goodbye", "uz": "xayr" }
],
   "A2": [
  { "en": "kill", "uz": "o‘ldirmoq" },
  { "en": "remain", "uz": "qolmoq" },
  { "en": "suggest", "uz": "taklif qilmoq" },
  { "en": "raise", "uz": "ko‘tarmoq" },
  { "en": "pass", "uz": "o‘tmoq" },
  { "en": "sell", "uz": "sotmoq" },
  { "en": "require", "uz": "talab qilmoq" },
  { "en": "report", "uz": "hisobot bermoq" },
  { "en": "decide", "uz": "qaror qilmoq" },
  { "en": "pull", "uz": "tortmoq" },
  { "en": "return", "uz": "qaytmoq" },
  { "en": "explain", "uz": "tushuntirmoq" },
  { "en": "hope", "uz": "umid qilmoq" },
  { "en": "develop", "uz": "rivojlantirmoq" },
  { "en": "carry", "uz": "ko‘tarmoq / olib yurmoq" },
  { "en": "break", "uz": "sindirmoq" },
  { "en": "receive", "uz": "qabul qilmoq" },
  { "en": "agree", "uz": "rozi bo‘lmoq" },
  { "en": "support", "uz": "qo‘llab-quvvatlamoq" },
  { "en": "hit", "uz": "urmoq" },
  { "en": "produce", "uz": "ishlab chiqarmoq" },
  { "en": "cover", "uz": "yopmoq" },
  { "en": "catch", "uz": "ushlamoq" },
  { "en": "draw", "uz": "chizmoq" },
  { "en": "choose", "uz": "tanlamoq" },
  { "en": "cause", "uz": "sabab bo‘lmoq" },
  { "en": "point", "uz": "ko‘rsatmoq / nuqta" },
  { "en": "realize", "uz": "anglamoq" },
  { "en": "place", "uz": "joylashtirmoq / joy" },
  { "en": "involve", "uz": "jalb qilmoq" },
  { "en": "believe", "uz": "ishonmoq" },
  { "en": "remember", "uz": "eslab qolmoq" },
  { "en": "forget", "uz": "unutmoq" },
  { "en": "build", "uz": "qurmoq" },
  { "en": "happen", "uz": "sodir bo‘lmoq" },
  { "en": "move", "uz": "harakatlanmoq / ko‘chmoq" },
  { "en": "change", "uz": "o‘zgartirmoq" },
  { "en": "improve", "uz": "yaxshilamoq" },
  { "en": "examine", "uz": "tekshirmoq" },
  { "en": "win", "uz": "g‘alaba qozonmoq" },
  { "en": "lose", "uz": "yo‘qotmoq / yutqazmoq" },
  { "en": "join", "uz": "qo‘shilmoq" },
  { "en": "train", "uz": "mashq qilmoq / tayyorlamoq" },
  { "en": "travel", "uz": "sayohat qilmoq" },
  { "en": "enjoy", "uz": "zavqlanmoq" },
  { "en": "decide", "uz": "qaror qilmoq" },
  { "en": "explain", "uz": "tushuntirmoq" },
  { "en": "discuss", "uz": "muhokama qilmoq" },
  { "en": "imagine", "uz": "tasavvur qilmoq" },
  { "en": "offer", "uz": "taklif qilmoq" },
  { "en": "suggest", "uz": "maslahat bermoq" },
  { "en": "borrow", "uz": "qarz olmoq" },
  { "en": "lend", "uz": "qarz bermoq" },
  { "en": "invite", "uz": "taklif qilmoq" },
  { "en": "explain", "uz": "izohlab bermoq" },
  { "en": "choose", "uz": "tanlab olmoq" },
  { "en": "decide", "uz": "hal qilmoq" },
  { "en": "happen", "uz": "ro‘y bermoq" },
  { "en": "prefer", "uz": "afzal ko‘rmoq" },
  { "en": "continue", "uz": "davom ettirmoq" },
  { "en": "describe", "uz": "tasvirlab bermoq" },
  { "en": "explain", "uz": "tushuntirmoq" },
  { "en": "arrive", "uz": "yetib kelmoq" },
  { "en": "leave", "uz": "ketmoq" },
  { "en": "spend", "uz": "sarflamoq" },
  { "en": "send", "uz": "yubormoq" },
  { "en": "stay", "uz": "qolmoq" },
  { "en": "enjoy", "uz": "rohatlanmoq" },
  { "en": "examine", "uz": "ko‘zdan kechirmoq" },
  { "en": "clean", "uz": "tozalamoq" },
  { "en": "wash", "uz": "yuvmoq" },
  { "en": "cut", "uz": "kesmoq" },
  { "en": "repair", "uz": "tuzatmoq" },
  { "en": "close", "uz": "yopmoq" },
  { "en": "open", "uz": "ochmoq" },
  { "en": "explain", "uz": "izoh bermoq" },
  { "en": "help", "uz": "yordam qilmoq" },
  { "en": "enjoy", "uz": "bahramand bo‘lmoq" },
  { "en": "invite", "uz": "taklif qilmoq" },
  { "en": "plan", "uz": "rejalashtirmoq" },
  { "en": "visit", "uz": "tashrif buyurmoq" },
  { "en": "arrive", "uz": "yetib kelmoq" },
  { "en": "wait", "uz": "kutmoq" },
  { "en": "drive", "uz": "haydamoq" },
  { "en": "ride", "uz": "minmoq" },
  { "en": "choose", "uz": "tanlamoq" },
  { "en": "hope", "uz": "umid qilmoq" },
  { "en": "decide", "uz": "qaror qilmoq" },
  { "en": "understand", "uz": "tushunmoq" },
  { "en": "prefer", "uz": "afzal bilmoq" },
  { "en": "belong", "uz": "tegishli bo‘lmoq" },
  { "en": "cost", "uz": "narx bo‘lmoq" },
  { "en": "save", "uz": "saqlamoq / tejamoq" },
  { "en": "spend", "uz": "pul sarflamoq" },
  { "en": "fill", "uz": "to‘ldirmoq" },
  { "en": "decide", "uz": "tanlov qilmoq" },
  { "en": "check", "uz": "tekshirmoq" },
  { "en": "push", "uz": "itarib yubormoq" },
  { "en": "carry", "uz": "tashimoq" },
  { "en": "repair", "uz": "tuzatmoq" },
  { "en": "explain", "uz": "izohlab tushuntirmoq" },
  { "en": "wait", "uz": "kutib turmoq" },
  { "en": "agree", "uz": "kelishmoq" },
  { "en": "believe", "uz": "ishonch bildirmoq" },
  { "en": "hope", "uz": "umid qilmoq" },
  { "en": "decide", "uz": "qaror qabul qilmoq" },
  { "en": "remember", "uz": "esda saqlamoq" },
  { "en": "forget", "uz": "unutib qo‘ymoq" },
  { "en": "explain", "uz": "tushuntirib bermoq" },
  { "en": "describe", "uz": "tasvirlamoq" },
  { "en": "plan", "uz": "reja tuzmoq" },
  { "en": "visit", "uz": "ko‘rmoq / tashrif buyurmoq" },
  { "en": "travel", "uz": "sayohatga chiqmoq" },
  { "en": "stay", "uz": "joyida qolmoq" },
  { "en": "enjoy", "uz": "zavqlanmoq" },
  { "en": "believe", "uz": "ishonmoq" },
  { "en": "hope", "uz": "umid bildirmoq" },
  { "en": "explain", "uz": "izoh bermoq" },
  { "en": "return", "uz": "orqaga qaytmoq" },
  { "en": "arrive", "uz": "yetib kelmoq" },
  { "en": "wait", "uz": "kutmoq" },
  { "en": "choose", "uz": "tanlamoq" },
  { "en": "describe", "uz": "ta’rif bermoq" }
]
,
"B1": [
  { "en": "achieve", "uz": "erishmoq" },
  { "en": "advantage", "uz": "afzallik" },
  { "en": "advice", "uz": "maslaxat" },
  { "en": "allow", "uz": "ruxsat bermoq" },
  { "en": "announce", "uz": "e'lon qilmoq" },
  { "en": "apologize", "uz": "uzr so‘ramoq" },
  { "en": "arrange", "uz": "tashkil qilmoq" },
  { "en": "attend", "uz": "qatnashmoq" },
  { "en": "available", "uz": "mavjud" },
  { "en": "average", "uz": "o‘rtacha" },
  { "en": "behavior", "uz": "xulq-atvor" },
  { "en": "believe", "uz": "ishonmoq" },
  { "en": "benefit", "uz": "foyda" },
  { "en": "borrow", "uz": "qarz olmoq" },
  { "en": "bright", "uz": "yorqin" },
  { "en": "calm", "uz": "tinch" },
  { "en": "careful", "uz": "ehtiyotkor" },
  { "en": "certain", "uz": "aniq" },
  { "en": "challenge", "uz": "sinov" },
  { "en": "choice", "uz": "tanlov" },
  { "en": "communicate", "uz": "aloqa qilmoq" },
  { "en": "community", "uz": "jamiyat" },
  { "en": "compare", "uz": "taqqoslamoq" },
  { "en": "complain", "uz": "shikoyat qilmoq" },
  { "en": "complete", "uz": "to‘ldirmoq" },
  { "en": "concentrate", "uz": "diqqatni jamlamoq" },
  { "en": "condition", "uz": "shart" },
  { "en": "confident", "uz": "ishonchli" },
  { "en": "connect", "uz": "ulamoq" },
  { "en": "consider", "uz": "ko‘rib chiqmoq" },
  { "en": "continue", "uz": "davom ettirmoq" },
  { "en": "convenient", "uz": "qulay" },
  { "en": "culture", "uz": "madaniyat" },
  { "en": "customer", "uz": "mijoz" },
  { "en": "decide", "uz": "qaror qilmoq" },
  { "en": "degree", "uz": "daraja" },
  { "en": "deliver", "uz": "yetkazmoq" },
  { "en": "depend", "uz": "bog‘liq bo‘lmoq" },
  { "en": "describe", "uz": "tasvirlamoq" },
  { "en": "design", "uz": "dizayn" },
  { "en": "develop", "uz": "rivojlantirmoq" },
  { "en": "difference", "uz": "farq" },
  { "en": "discuss", "uz": "muhokama qilmoq" },
  { "en": "education", "uz": "ta’lim" },
  { "en": "effect", "uz": "ta’sir" },
  { "en": "effort", "uz": "harakat" },
  { "en": "employ", "uz": "ishga olish" },
  { "en": "employee", "uz": "xodim" },
  { "en": "employer", "uz": "ish beruvchi" },
  { "en": "encourage", "uz": "rag‘batlantirmoq" },
  { "en": "enjoyable", "uz": "yoqimli" },
  { "en": "environment", "uz": "atrof-muhit" },
  { "en": "event", "uz": "voqeа" },
  { "en": "exactly", "uz": "aniq" },
  { "en": "experience", "uz": "tajriba" },
  { "en": "explain", "uz": "tushuntirmoq" },
  { "en": "expression", "uz": "ifoda" },
  { "en": "fact", "uz": "fakt" },
  { "en": "fail", "uz": "muvaffaqiyatsizlikka uchramoq" },
  { "en": "familiar", "uz": "tanish" },
  { "en": "fashion", "uz": "moda" },
  { "en": "fear", "uz": "qo‘rquv" },
  { "en": "feature", "uz": "xususiyat" },
  { "en": "flight", "uz": "parvoz" },
  { "en": "foreign", "uz": "xorijiy" },
  { "en": "forest", "uz": "o‘rmon" },
  { "en": "freedom", "uz": "erkinlik" },
  { "en": "friendly", "uz": "do‘stona" },
  { "en": "furniture", "uz": "mebel" },
  { "en": "future", "uz": "kelajak" },
  { "en": "goal", "uz": "maqsad" },
  { "en": "growth", "uz": "o‘sish" },
  { "en": "guest", "uz": "mehmon" },
  { "en": "habit", "uz": "odat" },
  { "en": "handle", "uz": "boshqarmoq" },
  { "en": "health", "uz": "salomatlik" },
  { "en": "helpful", "uz": "foydali" },
  { "en": "improve", "uz": "yaxshilamoq" },
  { "en": "include", "uz": "o‘z ichiga olmoq" },
  { "en": "increase", "uz": "oshmoq" },
  { "en": "independent", "uz": "mustaqil" },
  { "en": "influence", "uz": "ta’sir" },
  { "en": "injury", "uz": "jarohat" },
  { "en": "instead", "uz": "o‘rniga" },
  { "en": "interest", "uz": "qiziqish" },
  { "en": "international", "uz": "xalqaro" },
  { "en": "interview", "uz": "suhbat" },
  { "en": "introduce", "uz": "tanishtirmoq" },
  { "en": "invention", "uz": "ixtiro" },
  { "en": "journey", "uz": "sayohat" },
  { "en": "knowledge", "uz": "bilim" },
  { "en": "language", "uz": "til" },
  { "en": "lately", "uz": "yaqinda" },
  { "en": "lawyer", "uz": "huquqshunos" },
  { "en": "leadership", "uz": "rahbarlik" },
  { "en": "length", "uz": "uzunlik" },
  { "en": "level", "uz": "daraja" },
  { "en": "limit", "uz": "chegara" },
  { "en": "local", "uz": "mahalliy" },
  { "en": "lucky", "uz": "omadli" },
  { "en": "marry", "uz": "turmush qurmoq" },
  { "en": "material", "uz": "material" },
  { "en": "memory", "uz": "xotira" },
  { "en": "method", "uz": "usul" },
  { "en": "modern", "uz": "zamonaviy" },
  { "en": "moment", "uz": "lahza" },
  { "en": "national", "uz": "milliy" },
  { "en": "natural", "uz": "tabiiy" },
  { "en": "necessary", "uz": "zarur" },
  { "en": "nervous", "uz": "asabi" },
  { "en": "notice", "uz": "payqamoq" },
  { "en": "object", "uz": "narsa" },
  { "en": "opinion", "uz": "fikr" },
  { "en": "opportunity", "uz": "imkoniyat" },
  { "en": "organize", "uz": "tashkil etmoq" },
  { "en": "pain", "uz": "og‘riq" },
  { "en": "patient", "uz": "sabrli" },
  { "en": "peace", "uz": "tinchlik" },
  { "en": "perhaps", "uz": "balki" },
  { "en": "personal", "uz": "shaxsiy" },
  { "en": "pleasure", "uz": "zavq" },
  { "en": "population", "uz": "aholi" },
  { "en": "position", "uz": "lavozim" },
  { "en": "positive", "uz": "ijobiy" },
  { "en": "prepare", "uz": "tayyorlamoq" },
  { "en": "pressure", "uz": "bosim" },
  { "en": "probably", "uz": "ehtimol" },
  { "en": "product", "uz": "mahsulot" },
  { "en": "professional", "uz": "mutaxassis" },
  { "en": "promise", "uz": "va’da bermoq" },
  { "en": "protect", "uz": "himoya qilmoq" },
  { "en": "provide", "uz": "ta’minlamoq" },
  { "en": "purpose", "uz": "maqsad" },
  { "en": "quality", "uz": "sifat" },
  { "en": "quantity", "uz": "miqdor" },
  { "en": "quiet", "uz": "tinch" },
  { "en": "realize", "uz": "anglamoq" },
  { "en": "receive", "uz": "qabul qilmoq" },
  { "en": "recommend", "uz": "tavsiya qilmoq" },
  { "en": "reduce", "uz": "kamaytirmoq" },
  { "en": "refuse", "uz": "rad etmoq" },
  { "en": "regular", "uz": "muntazam" },
  { "en": "relationship", "uz": "munosabat" },
  { "en": "relax", "uz": "dam olmoq" },
  { "en": "replace", "uz": "almashtirmoq" },
  { "en": "report", "uz": "hisobot" },
  { "en": "require", "uz": "talab qilmoq" },
  { "en": "respect", "uz": "hurmat" },
  { "en": "responsible", "uz": "mas’ul" },
  { "en": "result", "uz": "natija" },
  { "en": "safe", "uz": "xavfsiz" },
  { "en": "salary", "uz": "maosh" },
  { "en": "scary", "uz": "qo‘rqinchli" },
  { "en": "search", "uz": "qidiruv" },
  { "en": "secret", "uz": "sir" },
  { "en": "selfish", "uz": "o‘z manfaatini o‘ylovchi" },
  { "en": "serious", "uz": "jiddiy" },
  { "en": "share", "uz": "bo‘lishmoq" },
  { "en": "shine", "uz": "yaltiramoq" },
  { "en": "shout", "uz": "baqirmoq" },
  { "en": "similar", "uz": "o‘xshash" },
  { "en": "simple", "uz": "oddiy" },
  { "en": "situation", "uz": "vaziyat" },
  { "en": "society", "uz": "jamiyat" },
  { "en": "solution", "uz": "yechim" },
  { "en": "someone", "uz": "kimdir" },
  { "en": "sometimes", "uz": "ba’zida" },
  { "en": "speech", "uz": "nutq" },
  { "en": "spend", "uz": "sarflamoq" },
  { "en": "staff", "uz": "xodimlar" },
  { "en": "strange", "uz": "g‘alati" },
  { "en": "stress", "uz": "stress" },
  { "en": "strong", "uz": "kuchli" },
  { "en": "success", "uz": "muvaffaqiyat" },
  { "en": "suggest", "uz": "taklif qilmoq" },
  { "en": "support", "uz": "qo‘llab-quvvatlamoq" },
  { "en": "suppose", "uz": "taxmin qilmoq" },
  { "en": "surprise", "uz": "ajablanmoq" },
  { "en": "terrible", "uz": "dahshatli" },
  { "en": "tidy", "uz": "ozoda" },
  { "en": "travel", "uz": "sayohat qilmoq" },
  { "en": "trust", "uz": "ishonmoq" },
  { "en": "truth", "uz": "haqiqat" },
  { "en": "typical", "uz": "odatdagi" },
  { "en": "usual", "uz": "odatiy" },
  { "en": "value", "uz": "qiymat" },
  { "en": "variety", "uz": "turfa xil" },
  { "en": "waste", "uz": "isrof" },
  { "en": "weather", "uz": "ob-havo" },
  { "en": "weight", "uz": "vazn" },
  { "en": "welcome", "uz": "xush kelibsiz" },
  { "en": "wonder", "uz": "hayron bo‘lmoq" },
  { "en": "worry", "uz": "xavotirlanmoq" },
  { "en": "worth", "uz": "arzimoq" },
  { "en": "youth", "uz": "yoshlik" }
]
,
   "B2": [
  { "en": "abandon", "uz": "tashlamoq, voz kechmoq" },
  { "en": "absolute", "uz": "mutlaqo, butunlay" },
  { "en": "absorb", "uz": "so‘rib olmoq" },
  { "en": "abstract", "uz": "mavhum" },
  { "en": "academic", "uz": "ilmiy, akademik" },
  { "en": "accent", "uz": "nutqdagi urg‘u" },
  { "en": "acceptable", "uz": "qabul qilinarli" },
  { "en": "accidentally", "uz": "tasodifan" },
  { "en": "accommodate", "uz": "joylashtirmoq; moslashtirmoq" },
  { "en": "accompany", "uz": "hamroh bo‘lmoq" },
  { "en": "accomplish", "uz": "bajarmoq, erishmoq" },
  { "en": "account", "uz": "hisob; hisoblamoq" },
  { "en": "accountant", "uz": "buqaruvchi" },
  { "en": "accuracy", "uz": "aniqlik" },
  { "en": "accurate", "uz": "aniq, to‘g‘ri" },
  { "en": "accurately", "uz": "aniq tarzda" },
  { "en": "accuse", "uz": "ayblamoq" },
  { "en": "acknowledge", "uz": "tan olmoq" },
  { "en": "acquire", "uz": "egallamoq, qo‘lga kiritmoq" },
  { "en": "acre", "uz": "akr (yer o‘lchovi)" },
  { "en": "activate", "uz": "faollashtirmoq" },
  { "en": "actual", "uz": "haqiqiy" },
  { "en": "adapt", "uz": "moslashmoq, moslashtirmoq" },
  { "en": "addiction", "uz": "odatlanish" },
  { "en": "additional", "uz": "qo‘shimcha" },
  { "en": "additionally", "uz": "qo‘shimcha ravishda" },
  { "en": "address", "uz": "manzil; murojaat qilmoq" },
  { "en": "adequate", "uz": "yetarli" },
  { "en": "adequately", "uz": "yetarlicha" },
  { "en": "adjust", "uz": "moslamoq, sozlamoq" },
  { "en": "administration", "uz": "ma’muriyat, boshqaruv" },
  { "en": "adopt", "uz": "qabul qilmoq; asrab olmoq" },
  { "en": "advance", "uz": "oldinga surmoq; rivojlanmoq" },
  { "en": "advantage", "uz": "afzallik" },
  { "en": "adventure", "uz": "sarguzasht" },
  { "en": "advertising", "uz": "reklama" },
  { "en": "affair", "uz": "masala; voqea" },
  { "en": "affordable", "uz": "arzon, ebayilgan" },
  { "en": "afterwards", "uz": "keyinroq" },
  { "en": "aged", "uz": "yoshlari … bo‘lgan" },
  { "en": "agency", "uz": "agentlik; idora" },
  { "en": "agenda", "uz": "kun tartibi" },
  { "en": "aggressive", "uz": "hujumkor" },
  { "en": "agriculture", "uz": "qishloq xo‘jaligi" },
  { "en": "aid", "uz": "yordam" },
  { "en": "AIDS", "uz": "OITS" },
  { "en": "aircraft", "uz": "havo kemasi" },
  { "en": "alarm", "uz": "signal; xavotir" },
  { "en": "alien", "uz": "chet el; begona" },
  { "en": "alongside", "uz": "yonida, yonidan" },
  { "en": "alter", "uz": "o‘zgartirmoq" },
  { "en": "altogether", "uz": "butunlay, jami" },
  { "en": "ambitious", "uz": "intilishli" },
  { "en": "ambulance", "uz": "tez tibbiy yordam mashinasi" },
  { "en": "amount", "uz": "miqdor" },
  { "en": "amusing", "uz": "qiziqarli" },
  { "en": "analyst", "uz": "tahlilchi" },
  { "en": "ancestor", "uz": "ajdod" },
  { "en": "anger", "uz": "g‘azab" },
  { "en": "angle", "uz": "burchak; qirra" },
  { "en": "animation", "uz": "animatsiya" },
  { "en": "anniversary", "uz": "yillik sana" },
  { "en": "anticipate", "uz": "kutmoq; taxmin qilmoq" },
  { "en": "anxiety", "uz": "bezovtalik" },
  { "en": "anxious", "uz": "beqaror, tahlikali" },
  { "en": "apology", "uz": "kechirim so‘rash" },
  { "en": "apparent", "uz": "ko‘rinadigan; aniq" },
  { "en": "apparently", "uz": "ko‘rib turilganidek" },
  { "en": "appeal", "uz": "jzib, murojaat qilmoq" },
  { "en": "applicant", "uz": "ariza beruvchi" },
  { "en": "appoint", "uz": "tayinlamoq" },
  { "en": "appreciate", "uz": "qadriga yetmoq; minnatdor bo‘lmoq" },
  { "en": "approval", "uz": "ma’qullash" },
  { "en": "approve", "uz": "ma’qullamoq" },
  { "en": "arise", "uz": "paydo bo‘lmoq" },
  { "en": "armed", "uz": "qurollangan" },
  { "en": "arms", "uz": "qurollar" },
  { "en": "arrow", "uz": "ok" },
  { "en": "artificial", "uz": "sun’iy" },
  { "en": "artistic", "uz": "san’atga oid" },
  { "en": "artwork", "uz": "asarlari; san’at asari" },
  { "en": "ashamed", "uz": "uyalmoq" },
  { "en": "aspect", "uz": "qirra, jihat" },
  { "en": "assess", "uz": "baholamoq" },
  { "en": "assessment", "uz": "baholash; baho" },
  { "en": "asset", "uz": "mol-mulk; aktiv" },
  { "en": "assign", "uz": "vazifa bermoq" },
  { "en": "assistant", "uz": "yoramchi; yordamchi" },
  { "en": "associate", "uz": "bog‘lamoq; hamkor" },
  { "en": "associated", "uz": "bog‘langan, aloqador" },
  { "en": "association", "uz": "asoslashuv; uyushma" },
  { "en": "assume", "uz": "faraz qilmoq" },
  { "en": "assumption", "uz": "faraz" },
  { "en": "assure", "uz": "ishontirmoq" },
  { "en": "astonishing", "uz": "hayratlanarli" },
  { "en": "athletic", "uz": "sportga oid" },
  { "en": "atmosphere", "uz": "muqit; atmosfera" },
  { "en": "attitude", "uz": "munosabat; kayfiyat" },
  { "en": "attract", "uz": "jalb qilmoq" },
  { "en": "authority", "uz": "hokimiyat; vakolat" },
  { "en": "automatic", "uz": "avtomatik" },
  { "en": "available", "uz": "mavjud" },
  { "en": "average", "uz": "o‘rtacha" },
  { "en": "avoid", "uz": "qochmoq" },
  { "en": "await", "uz": "kutmoq" },
  { "en": "aware", "uz": "xabardor" },
  { "en": "awesome", "uz": "ajoyib" },
  { "en": "axis", "uz": "o‘q; markaziy chiziq" }
]
,
   "C1": [
  { "en": "abolish", "uz": "bekor qilmoq" },
  { "en": "abundant", "uz": "ko‘p, mo‘l" },
  { "en": "accelerate", "uz": "tezlashtirmoq" },
  { "en": "accessible", "uz": "kirish mumkin bo‘lgan" },
  { "en": "accomplish", "uz": "bajarib chiqmoq" },
  { "en": "acknowledge", "uz": "tan olmoq" },
  { "en": "acquisition", "uz": "qo‘lga kiritish" },
  { "en": "adhere", "uz": "yopishmoq, sodiq bo‘lmoq" },
  { "en": "adjacent", "uz": "yonma-yon" },
  { "en": "advocate", "uz": "himoya qilmoq" },
  { "en": "aggregate", "uz": "umumiy, yig‘indi" },
  { "en": "allege", "uz": "da’vo qilmoq" },
  { "en": "allocate", "uz": "ajratmoq" },
  { "en": "alter", "uz": "o‘zgartirmoq" },
  { "en": "ambiguous", "uz": "noaniq, ikki ma’noli" },
  { "en": "amend", "uz": "tuzatmoq, yaxshilamoq" },
  { "en": "ample", "uz": "yetarli, mo‘l" },
  { "en": "analogy", "uz": "o‘xshashlik" },
  { "en": "anticipate", "uz": "oldindan kutmoq" },
  { "en": "apparent", "uz": "aniq, ko‘rinadigan" },
  { "en": "appeal", "uz": "murojaat qilmoq" },
  { "en": "applicable", "uz": "tatbiq etiladigan" },
  { "en": "approximate", "uz": "taxminiy" },
  { "en": "arbitrary", "uz": "ixtiyoriy" },
  { "en": "assert", "uz": "qat’iy aytmoq" },
  { "en": "assess", "uz": "baholamoq" },
  { "en": "attain", "uz": "erishmoq" },
  { "en": "attribute", "uz": "xususiyat, belgi" },
  { "en": "authentic", "uz": "asl, haqiqiy" },
  { "en": "automated", "uz": "avtomatlashtirilgan" },
  { "en": "beneficial", "uz": "foydali" },
  { "en": "biased", "uz": "bir tomonlama, xolis emas" },
  { "en": "blend", "uz": "aralashmoq" },
  { "en": "brisk", "uz": "tez, chaqqon" },
  { "en": "bulk", "uz": "asosiy qism, katta miqdor" },
  { "en": "capability", "uz": "qobiliyat" },
  { "en": "cease", "uz": "to‘xtamoq" },
  { "en": "clarity", "uz": "aniqlik, ravshanlik" },
  { "en": "coherent", "uz": "mos, bir-biriga bog‘liq" },
  { "en": "coincide", "uz": "to‘g‘ri kelmoq" },
  { "en": "commodity", "uz": "tovar, mahsulot" },
  { "en": "comparable", "uz": "taqqoslanadigan" },
  { "en": "compensate", "uz": "qoplamoq, to‘lamoq" },
  { "en": "compile", "uz": "tuzmoq, yig‘moq" },
  { "en": "complement", "uz": "to‘ldirmoq" },
  { "en": "comprise", "uz": "o‘z ichiga olmoq" },
  { "en": "conceive", "uz": "tasavvur qilmoq" },
  { "en": "concurrent", "uz": "bir vaqtda" },
  { "en": "confine", "uz": "cheklamoq" },
  { "en": "conform", "uz": "moslashmoq" },
  { "en": "confront", "uz": "duch kelmoq" },
  { "en": "consecutive", "uz": "ketma-ket" },
  { "en": "consent", "uz": "rozilik bermoq" },
  { "en": "considerable", "uz": "sezilarli" },
  { "en": "constitute", "uz": "tashkil qilmoq" },
  { "en": "constraint", "uz": "cheklov" },
  { "en": "contend", "uz": "kurashmoq, da’vo qilmoq" },
  { "en": "contradict", "uz": "zid bo‘lmoq" },
  { "en": "contrary", "uz": "teskari" },
  { "en": "converse", "uz": "gaplashmoq" },
  { "en": "convey", "uz": "yetkazmoq, ifoda qilmoq" },
  { "en": "convince", "uz": "ishontirmoq" },
  { "en": "core", "uz": "markaz, asos" },
  { "en": "crucial", "uz": "muhim" },
  { "en": "currency", "uz": "valyuta" },
  { "en": "deduce", "uz": "xulosa chiqarmoq" },
  { "en": "defy", "uz": "qarshi chiqmoq" },
  { "en": "denote", "uz": "anglatmoq" },
  { "en": "derive", "uz": "olmoq, kelib chiqmoq" },
  { "en": "diminish", "uz": "kamaytirmoq" },
  { "en": "discrete", "uz": "alohida" },
  { "en": "displace", "uz": "joyidan surmoq" },
  { "en": "diverse", "uz": "turli-tuman" },
  { "en": "domain", "uz": "soha, hudud" },
  { "en": "dominate", "uz": "ustunlik qilmoq" },
  { "en": "duration", "uz": "davomiylik" },
  { "en": "elaborate", "uz": "batafsil tushuntirmoq" },
  { "en": "eliminate", "uz": "yo‘q qilmoq" },
  { "en": "emerge", "uz": "paydo bo‘lmoq" },
  { "en": "empirical", "uz": "tajribaviy" },
  { "en": "encounter", "uz": "uchrashmoq, duch kelmoq" },
  { "en": "enhance", "uz": "yaxshilamoq, kuchaytirmoq" },
  { "en": "enormous", "uz": "ulkan, juda katta" },
  { "en": "ensure", "uz": "ta’minlamoq" },
  { "en": "equivalent", "uz": "teng, mos" },
  { "en": "erode", "uz": "yemirilmoq" },
  { "en": "establish", "uz": "barpo qilmoq" },
  { "en": "estimate", "uz": "baholamoq, taxmin qilmoq" },
  { "en": "evident", "uz": "aniq, ravshan" },
  { "en": "evolve", "uz": "rivojlanmoq" },
  { "en": "exceed", "uz": "oshmoq" },
  { "en": "exclude", "uz": "chiqarib tashlamoq" },
  { "en": "exhibit", "uz": "namoyish qilmoq" },
  { "en": "explicit", "uz": "aniq, ochiq" },
  { "en": "expose", "uz": "fosh qilmoq" },
  { "en": "extract", "uz": "ajratmoq, tortib olmoq" },
  { "en": "facilitate", "uz": "yengillashtirmoq" },
  { "en": "fluctuate", "uz": "o‘zgarib turmoq" },
  { "en": "framework", "uz": "tuzilma" },
  { "en": "generate", "uz": "yaratmoq" },
  { "en": "guarantee", "uz": "kafolat bermoq" },
  { "en": "highlight", "uz": "urg‘u bermoq" },
  { "en": "hypothesis", "uz": "taxmin, gipoteza" },
  { "en": "identical", "uz": "bir xil" },
  { "en": "illustrate", "uz": "ko‘rsatmoq, misol keltirmoq" },
  { "en": "imply", "uz": "nazarda tutmoq" },
  { "en": "incentive", "uz": "rag‘bat" },
  { "en": "incline", "uz": "moyil bo‘lmoq" },
  { "en": "incorporate", "uz": "qo‘shmoq, birlashtirmoq" },
  { "en": "indicate", "uz": "ko‘rsatmoq" },
  { "en": "inevitable", "uz": "muqarrar" },
  { "en": "infer", "uz": "xulosa qilmoq" },
  { "en": "inhibit", "uz": "to‘sqinlik qilmoq" },
  { "en": "initial", "uz": "boshlang‘ich" },
  { "en": "inspect", "uz": "tekshirmoq" },
  { "en": "instance", "uz": "misol" },
  { "en": "integrate", "uz": "birlashtirmoq" },
  { "en": "intervene", "uz": "aralashmoq" },
  { "en": "intrinsic", "uz": "ichki, tabiiy" },
  { "en": "investigate", "uz": "tekshirmoq, surishtirmoq" },
  { "en": "invoke", "uz": "chaqirmoq, iltijo qilmoq" },
  { "en": "involve", "uz": "jalb qilmoq" },
  { "en": "justify", "uz": "oqlamoq" },
  { "en": "legislate", "uz": "qonun chiqarmoq" }
   ]
  },
  "grammar": 
   {
  "A1": {
    "To be": {
      "rule_uz": "'To be' fe'li mavjudlik, holat yoki kimnidir aniqlash uchun ishlatiladi. Uning shakllari: 'am', 'is', 'are'. 'Am' – I bilan, 'is' – he/she/it bilan, 'are' – we/you/they bilan ishlatiladi. Inkor shakli uchun 'not' qo‘shiladi: I am not, he isn’t, they aren’t. Savol shaklida 'to be' oldinga chiqadi: Is he a doctor?",
      "structure": "Affirmative: S + am/is/are + complement. | Negative: S + am/is/are + not + complement. | Question: Am/Is/Are + S + complement?",
      "examples": [
        { "en": "I am a student.", "uz": "Men talaba." },
        { "en": "She is a teacher.", "uz": "U o‘qituvchi." },
        { "en": "He is tired.", "uz": "U charchagan." },
        { "en": "We are happy.", "uz": "Biz baxtlimiz." },
        { "en": "They are at home.", "uz": "Ular uyda." },
        { "en": "I am not hungry.", "uz": "Men och emasman." },
        { "en": "She isn’t busy.", "uz": "U band emas." },
        { "en": "Are you ready?", "uz": "Siz tayyormisiz?" },
        { "en": "Is he your brother?", "uz": "U sizning akangizmi?" },
        { "en": "We are not late.", "uz": "Biz kech qolmadik." }
      ]
    },

    "Present Simple": {
      "rule_uz": "Present Simple zamoni odatdagi, takrorlanadigan yoki doimiy holatdagi harakatlarni ifodalaydi. Fe’lning 3-shaxs birlik shaklida -s qo‘shimchasi qo‘shiladi. Inkor uchun 'don’t/doesn’t' ishlatiladi. Savol uchun esa 'Do/Does' oldinga chiqadi.",
      "structure": "Affirmative: S + V (he/she/it + V+s). | Negative: S + don’t/doesn’t + V. | Question: Do/Does + S + V?",
      "examples": [
        { "en": "I go to school every day.", "uz": "Men har kuni maktabga boraman." },
        { "en": "He works in an office.", "uz": "U ofisda ishlaydi." },
        { "en": "She likes coffee.", "uz": "U qahvani yoqtiradi." },
        { "en": "We play football on Sundays.", "uz": "Biz yakshanba kunlari futbol o‘ynaymiz." },
        { "en": "They study English.", "uz": "Ular ingliz tilini o‘rganadilar." },
        { "en": "It rains a lot here.", "uz": "Bu yerda ko‘p yomg‘ir yog‘adi." },
        { "en": "She doesn’t eat meat.", "uz": "U go‘sht yemaydi." },
        { "en": "I don’t like tea.", "uz": "Men choyni yoqtirmayman." },
        { "en": "Do you play the guitar?", "uz": "Siz gitara chalishingizni yoqtirasizmi?" },
        { "en": "Does he live in London?", "uz": "U Londonda yashaydimi?" }
      ]
    },

    "Plural Nouns": {
      "rule_uz": "Ko‘plik otlar (Plural nouns) odatda -s yoki -es qo‘shimchasi bilan yasaladi. Agar so‘z 'y' bilan tugasa va undan oldingi harf undosh bo‘lsa, 'y' o‘rniga 'ies' yoziladi (baby → babies). Ba’zi so‘zlar noaniq shaklda o‘zgaradi (child → children, man → men).",
      "structure": "Singular + s/es = Plural | -y → -ies (baby → babies) | Irregular forms: man → men, woman → women.",
      "examples": [
        { "en": "One cat, two cats.", "uz": "Bitta mushuk, ikkita mushuk." },
        { "en": "I have three books.", "uz": "Menda uchta kitob bor." },
        { "en": "There are many apples.", "uz": "Ko‘p olma bor." },
        { "en": "The boys are playing.", "uz": "O‘g‘il bolalar o‘ynashyapti." },
        { "en": "My friends are kind.", "uz": "Mening do‘stlarim mehribon." },
        { "en": "Those men are strong.", "uz": "U erkaklar kuchli." },
        { "en": "We saw two buses.", "uz": "Biz ikkita avtobusni ko‘rdik." },
        { "en": "There are children in the park.", "uz": "Bog‘da bolalar bor." },
        { "en": "These apples are red.", "uz": "Bu olmalar qizil." },
        { "en": "I like flowers.", "uz": "Men gullarni yoqtiraman." }
      ]
    },

    "There is / There are": {
      "rule_uz": "'There is' — birlik otlar bilan, 'There are' — ko‘plik otlar bilan ishlatiladi. Ular nimanidir mavjudligini bildiradi. Inkor uchun 'isn’t' yoki 'aren’t' ishlatiladi. Savolda esa 'Is there?' yoki 'Are there?' bo‘ladi.",
      "structure": "Affirmative: There is/are + noun. | Negative: There isn’t/aren’t + noun. | Question: Is/Are there + noun?",
      "examples": [
        { "en": "There is a book on the table.", "uz": "Stol ustida kitob bor." },
        { "en": "There are three cars outside.", "uz": "Tashqarida uchta mashina bor." },
        { "en": "There is a cat in the garden.", "uz": "Bog‘da mushuk bor." },
        { "en": "There are many people here.", "uz": "Bu yerda ko‘p odam bor." },
        { "en": "There isn’t any milk.", "uz": "Sut yo‘q." },
        { "en": "There aren’t any chairs.", "uz": "Hech qanday stul yo‘q." },
        { "en": "Is there a bank near here?", "uz": "Bu yerda yaqin atrofda bank bormi?" },
        { "en": "Are there apples in the fridge?", "uz": "Muzlatkichda olmalar bormi?" },
        { "en": "There is a park in my city.", "uz": "Mening shahrimda park bor." },
        { "en": "There are two schools in my area.", "uz": "Mening hududimda ikki maktab bor." }
      ]
    },

    "Can / Can't": {
      "rule_uz": "'Can' imkoniyat, ruxsat yoki qobiliyatni ifodalaydi. 'Can't' esa uning inkoridir. Har qanday shaxs uchun fe’lning asosiy shakli bilan ishlatiladi. Savol shaklida 'Can' oldinga chiqadi.",
      "structure": "Affirmative: S + can + V. | Negative: S + can’t + V. | Question: Can + S + V?",
      "examples": [
        { "en": "I can swim.", "uz": "Men suza olaman." },
        { "en": "She can play the piano.", "uz": "U pianino chaloladi." },
        { "en": "They can speak English.", "uz": "Ular ingliz tilida gapira oladilar." },
        { "en": "We can drive.", "uz": "Biz mashina hayday olamiz." },
        { "en": "He can’t cook.", "uz": "U ovqat pishira olmaydi." },
        { "en": "I can’t run fast.", "uz": "Men tez yugura olmayman." },
        { "en": "Can you help me?", "uz": "Menga yordam bera olasizmi?" },
        { "en": "Can she dance?", "uz": "U raqsga tushi oladimi?" },
        { "en": "I can write a letter.", "uz": "Men xat yozishim mumkin." },
        { "en": "They can’t come today.", "uz": "Ular bugun kela olishmaydi." }
      ]
    }
  },
  
  "A2": {
    "Past Simple": {
      "rule_uz": "Past Simple — bu zamon o‘tgan vaqtda bo‘lgan harakatlarni ifodalash uchun ishlatiladi. Odatda vaqt so‘zlari bilan birga ishlatiladi: yesterday, last week, ago, in 2020 va hokazo. Fe’lning 2-shakli (past form) ishlatiladi. Inkorda 'did not' (didn’t), savolda esa 'Did' ishlatiladi.",
      "structure": "S + V2 + O / Did + S + V1 + O / S + did not + V1 + O",
      "examples": [
        { "en": "I visited Samarkand last year.", "uz": "Men o‘tgan yili Samarqandga bordim." },
        { "en": "She studied English yesterday.", "uz": "U kecha ingliz tilini o‘rgandi." },
        { "en": "They played football in the park.", "uz": "Ular bog‘da futbol o‘ynashdi." },
        { "en": "He didn’t watch TV.", "uz": "U televizor ko‘rmadi." },
        { "en": "Did you go to school?", "uz": "Sen maktabga bordingmi?" },
        { "en": "We lived in Namangan.", "uz": "Biz Namanganda yashadik." },
        { "en": "My mother cooked plov.", "uz": "Onam palov pishirdi." },
        { "en": "They didn’t like the food.", "uz": "Ular ovqatni yoqtirishmadi." },
        { "en": "Did she come yesterday?", "uz": "U kecha keldimi?" },
        { "en": "I finished my homework.", "uz": "Men uy vazifamni tugatdim." }
      ]
    },

    "Present Continuous": {
      "rule_uz": "Present Continuous — hozirgi paytda davom etayotgan harakatni ifodalaydi. U 'am/is/are + fe’l + ing' shaklida tuziladi. Odatda now, at the moment, right now kabi vaqt ifodalari bilan ishlatiladi.",
      "structure": "S + am/is/are + V-ing + O",
      "examples": [
        { "en": "I am studying English now.", "uz": "Men hozir ingliz tilini o‘rganayapman." },
        { "en": "She is watching TV.", "uz": "U televizor ko‘rayapti." },
        { "en": "They are playing football.", "uz": "Ular futbol o‘ynashyapti." },
        { "en": "He isn’t sleeping.", "uz": "U uxlamayapti." },
        { "en": "Are you listening?", "uz": "Siz tinglayapsizmi?" },
        { "en": "We are learning grammar.", "uz": "Biz grammatika o‘rganayapmiz." },
        { "en": "It is raining.", "uz": "Yomg‘ir yog‘ayapti." },
        { "en": "I’m not watching YouTube.", "uz": "Men YouTube ko‘rayotganim yo‘q." },
        { "en": "She is talking on the phone.", "uz": "U telefonda gaplashayapti." },
        { "en": "They are studying for the test.", "uz": "Ular testga tayyorlanishyapti." }
      ]
    },

    "Future Simple": {
      "rule_uz": "Future Simple — kelajakdagi reja yoki qarorlarni ifodalaydi. 'Will' yordamchi fe’li ishlatiladi. Inkorda 'will not' (won’t), savolda esa 'Will' boshida bo‘ladi.",
      "structure": "S + will + V1 + O / Will + S + V1 + O / S + will not + V1 + O",
      "examples": [
        { "en": "I will call you tomorrow.", "uz": "Men ertaga senga qo‘ng‘iroq qilaman." },
        { "en": "She will visit London next year.", "uz": "U keyingi yili Londonga boradi." },
        { "en": "We will meet at 6 o’clock.", "uz": "Biz soat 6 da uchrashamiz." },
        { "en": "He won’t go to work today.", "uz": "U bugun ishga bormaydi." },
        { "en": "Will they come to the party?", "uz": "Ular bazmga kelishadimi?" },
        { "en": "I will help you.", "uz": "Men senga yordam beraman." },
        { "en": "She won’t study tonight.", "uz": "U bugun kechasi o‘qimaydi." },
        { "en": "We will travel soon.", "uz": "Biz tez orada sayohat qilamiz." },
        { "en": "Will you join us?", "uz": "Siz bizga qo‘shilasizmi?" },
        { "en": "They will start a new project.", "uz": "Ular yangi loyiha boshlaydilar." }
      ]
    },

    "Comparatives and Superlatives": {
      "rule_uz": "Comparative va Superlative sifatlar taqqoslash uchun ishlatiladi. 'er' yoki 'more' bilan Comparative, 'est' yoki 'most' bilan Superlative shakli yasaladi. Comparative — 2 ta narsani, Superlative — 3 yoki undan ortiq narsani taqqoslaydi.",
      "structure": "Adj + er + than / more + Adj + than / the + Adj + est / the most + Adj",
      "examples": [
        { "en": "My house is bigger than yours.", "uz": "Mening uyim siznikidan kattaroq." },
        { "en": "This book is more interesting than that one.", "uz": "Bu kitob u kitobdan qiziqarliroq." },
        { "en": "He is taller than his brother.", "uz": "U akasidan bo‘yliroq." },
        { "en": "Today is the coldest day.", "uz": "Bugun eng sovuq kun." },
        { "en": "She is the most beautiful girl.", "uz": "U eng chiroyli qiz." },
        { "en": "My car is faster than yours.", "uz": "Mening mashinam siznikidan tezroq." },
        { "en": "This task is easier than that one.", "uz": "Bu topshiriq u topshiriqdan osonroq." },
        { "en": "Everest is the highest mountain.", "uz": "Everest eng baland tog‘." },
        { "en": "He is more polite than his friend.", "uz": "U do‘stidan muloyimroq." },
        { "en": "That was the most exciting day.", "uz": "Bu eng hayajonli kun edi." }
      ]
    },

    "Prepositions of Time": {
      "rule_uz": "Prepositions of time — vaqtni bildiruvchi predloglar. Eng ko‘p ishlatiladiganlari: 'in', 'on', 'at'. 'In' — oy, yil, asrlar bilan; 'on' — kun va sanalar bilan; 'at' — aniq vaqt bilan ishlatiladi.",
      "structure": "in + month/year; on + day/date; at + exact time",
      "examples": [
        { "en": "I was born in 2010.", "uz": "Men 2010 yilda tug‘ilganman." },
        { "en": "She goes to school at 8 o’clock.", "uz": "U maktabga soat 8 da boradi." },
        { "en": "We have English lessons on Monday.", "uz": "Bizda dushanba kuni ingliz tili darsi bo‘ladi." },
        { "en": "They met in winter.", "uz": "Ular qishda uchrashishgan." },
        { "en": "I’ll call you at night.", "uz": "Men senga kechasi qo‘ng‘iroq qilaman." },
        { "en": "The meeting is on Friday.", "uz": "Uchrashuv juma kuni." },
        { "en": "He was born in May.", "uz": "U may oyida tug‘ilgan." },
        { "en": "Let’s meet at noon.", "uz": "Keling, soat 12 da uchrashamiz." },
        { "en": "My birthday is on June 10th.", "uz": "Mening tug‘ilgan kunim 10-iyun." },
        { "en": "We travel in summer.", "uz": "Biz yozda sayohat qilamiz." }
      ]
    }
  },
   

  "B1": {
  "Present Perfect": {
    "rule_uz": "Present Perfect zamoni — o'tgan ish hozirgi natijaga ega bo'lganda ishlatiladi. Asosan 'have/has + V3' shaklida tuziladi. U hozirgacha tugagan, ammo natijasi sezilayotgan ishni bildiradi.",
    "structure": "S + have/has + V3 (+ O)",
    "examples": [
      {"en": "I have finished my homework.", "uz": "Men uy vazifamni tugatdim."},
      {"en": "She has gone to school.", "uz": "U maktabga ketdi."},
      {"en": "We have eaten breakfast.", "uz": "Biz nonushta qildik."},
      {"en": "They have visited London.", "uz": "Ular Londonga tashrif buyurishdi."},
      {"en": "He has just arrived.", "uz": "U hozirgina keldi."},
      {"en": "I have never seen that movie.", "uz": "Men u filmni hech qachon ko‘rmaganman."},
      {"en": "We have met before.", "uz": "Biz ilgari uchrashganmiz."},
      {"en": "She has already finished her project.", "uz": "U loyihasini allaqachon tugatgan."},
      {"en": "They have lived here for five years.", "uz": "Ular bu yerda besh yildan beri yashashadi."},
      {"en": "You have broken my phone!", "uz": "Siz mening telefonimni sindirdingiz!"}
    ]
  },

  "Modal verbs (should/could)": {
    "rule_uz": "Modal fe’llar (should, could) maslahatlarga yoki imkoniyatlarga ishora qiladi. 'Should' — tavsiya, 'could' — o‘tgan yoki mumkinlikni bildiradi.",
    "structure": "S + should/could + V1 (+ O)",
    "examples": [
      {"en": "You should study more.", "uz": "Siz ko‘proq o‘qishingiz kerak."},
      {"en": "He could run very fast.", "uz": "U juda tez yugura olgan."},
      {"en": "They should go to the doctor.", "uz": "Ular doktorga borishlari kerak."},
      {"en": "I could swim when I was five.", "uz": "Men besh yoshimda suza olardim."},
      {"en": "We should save more money.", "uz": "Biz ko‘proq pul tejashimiz kerak."},
      {"en": "You could try again.", "uz": "Siz yana urinib ko‘rishingiz mumkin."},
      {"en": "She should not be late.", "uz": "U kechikmasligi kerak."},
      {"en": "They could help us tomorrow.", "uz": "Ular ertaga bizga yordam berishlari mumkin."},
      {"en": "He should eat healthy food.", "uz": "U sog‘lom ovqat yeyishi kerak."},
      {"en": "I could hear the sound clearly.", "uz": "Men tovushni aniq eshita oldim."}
    ]
  },

  "Passive Voice (intro)": {
    "rule_uz": "Passive Voice — bajaruvchi muhim bo‘lmaganda ishlatiladi. Asosiy tuzilma: be + V3. E’tibor faoliyatning o‘zida bo‘ladi, kim bajarganida emas.",
    "structure": "S + am/is/are + V3 (+ by + doer)",
    "examples": [
      {"en": "The letter is written by Sara.", "uz": "Xat Sara tomonidan yozilgan."},
      {"en": "The cake is made by my mom.", "uz": "Tort onam tomonidan tayyorlangan."},
      {"en": "The room is cleaned every day.", "uz": "Xona har kuni tozalanadi."},
      {"en": "English is spoken here.", "uz": "Bu yerda ingliz tili so‘zlanadi."},
      {"en": "The car is repaired by John.", "uz": "Mashina Jon tomonidan ta’mirlanadi."},
      {"en": "The book was written in 1990.", "uz": "Kitob 1990-yilda yozilgan."},
      {"en": "Milk is sold in this shop.", "uz": "Bu do‘konda sut sotiladi."},
      {"en": "The house is built by workers.", "uz": "Uy ishchilar tomonidan qurilgan."},
      {"en": "The song is sung by her.", "uz": "Qo‘shiq u tomonidan kuylanadi."},
      {"en": "The flowers are watered daily.", "uz": "Gullar har kuni sug‘oriladi."}
    ]
  },

  "Reported Speech (intro)": {
    "rule_uz": "Reported Speech — kimningdir so‘zlarini qayta aytishda ishlatiladi. Asosan zamon orqaga suriladi: say → said that, go → went.",
    "structure": "S + said (that) + S + V (past form)",
    "examples": [
      {"en": "He said that he was tired.", "uz": "U charchaganini aytdi."},
      {"en": "She said that she liked coffee.", "uz": "U qahvani yoqtirishini aytdi."},
      {"en": "They said that they were busy.", "uz": "Ular band ekanliklarini aytishdi."},
      {"en": "I said that I would call her.", "uz": "Men unga qo‘ng‘iroq qilishimni aytdim."},
      {"en": "She told me that she had lost her keys.", "uz": "U menga kalitlarini yo‘qotganini aytdi."},
      {"en": "He said that he didn’t know.", "uz": "U bilmasligini aytdi."},
      {"en": "They said that they had seen the movie.", "uz": "Ular filmni ko‘rganliklarini aytishdi."},
      {"en": "I told her that it was late.", "uz": "Men unga kech bo‘lganini aytdim."},
      {"en": "She said that she couldn’t come.", "uz": "U kela olmasligini aytdi."},
      {"en": "He said that he was hungry.", "uz": "U ochligini aytdi."}
    ]
  },

  "Conditionals 0 & 1": {
    "rule_uz": "Conditionals 0 va 1 — sabab va natija ifodalaydi. 0-type — doimiy holatlar, 1-type — ehtimoliy holatlar uchun.",
    "structure": "If + Present, Present / If + Present, will + V1",
    "examples": [
      {"en": "If it rains, we stay home.", "uz": "Agar yomg‘ir yog‘sa, uyda qolamiz."},
      {"en": "If I see him, I will tell him.", "uz": "Agar uni ko‘rsam, aytaman."},
      {"en": "If you heat water, it boils.", "uz": "Agar suvni qizdirsang, u qaynaydi."},
      {"en": "If I study, I will pass the test.", "uz": "Agar o‘qisam, testdan o‘taman."},
      {"en": "If he runs fast, he wins.", "uz": "Agar u tez yugursa, yutadi."},
      {"en": "If you don’t eat, you get hungry.", "uz": "Agar ovqat yemasan, och bo‘lasan."},
      {"en": "If it is cold, we wear coats.", "uz": "Agar sovuq bo‘lsa, palto kiyamiz."},
      {"en": "If she works hard, she will succeed.", "uz": "Agar u mehnatsevar bo‘lsa, muvaffaqiyat qozonadi."},
      {"en": "If I have time, I will help you.", "uz": "Agar vaqtim bo‘lsa, yordam beraman."},
      {"en": "If you mix red and blue, you get purple.", "uz": "Agar qizil va ko‘kni aralashtirsang, binafsha hosil bo‘ladi."}
    ]
  }
}
,
  "B2": {
  "Past Perfect": {
    "rule_uz": "Past Perfect — bu o‘tgan zamonda boshqa bir o‘tgan hodisadan oldin bo‘lgan ishni ifodalaydi. Odatda 'had + past participle' (had done) shaklida ishlatiladi. Bu zamon hikoya yoki voqealar ketma-ketligini tushuntirishda ishlatiladi.",
    "structure": "S + had + V3 + O",
    "examples": [
      {"en": "She had left before I arrived.", "uz": "Men kelishimdan oldin u ketgan edi."},
      {"en": "They had eaten all the food.", "uz": "Ular barcha ovqatni yeyishgan edi."},
      {"en": "I had never seen such a movie.", "uz": "Men bunday filmni hech qachon ko‘rmagan edim."},
      {"en": "He had finished his homework before dinner.", "uz": "U kechki ovqatdan oldin uy vazifasini tugatgan edi."},
      {"en": "We had already met before the meeting.", "uz": "Biz uchrashuvdan oldin allaqachon tanishgan edik."},
      {"en": "She had gone home when I called.", "uz": "Men qo‘ng‘iroq qilganimda, u uyiga ketgan edi."},
      {"en": "I had studied English for two years before moving abroad.", "uz": "Men chet elga ko‘chishdan oldin ikki yil ingliz tilini o‘rgangan edim."},
      {"en": "The train had left when we arrived.", "uz": "Biz yetganimizda poyezd ketgan edi."},
      {"en": "They had not finished their project yet.", "uz": "Ular hali loyihani tugatishmagan edi."},
      {"en": "Had you ever tried sushi before Japan?", "uz": "Yaponiyaga borishdan oldin sushini tatib ko‘rganmiding?"}
    ]
  },
  "Past Continuous": {
    "rule_uz": "Past Continuous — o‘tgan vaqtda ma’lum bir paytda davom etayotgan harakatni ifodalaydi. 'was/were + V-ing' shaklida yoziladi. Odatda boshqa voqea bilan birga yoki uni to‘xtatuvchi holatda ishlatiladi.",
    "structure": "S + was/were + V-ing + O",
    "examples": [
      {"en": "I was reading a book when you called.", "uz": "Siz qo‘ng‘iroq qilganingizda men kitob o‘qiyotgan edim."},
      {"en": "They were watching TV all evening.", "uz": "Ular butun kechani televizor ko‘rish bilan o‘tkazishdi."},
      {"en": "She was cooking while he was cleaning.", "uz": "U pishirayotgan paytda u tozalayotgan edi."},
      {"en": "We were studying for the exam.", "uz": "Biz imtihon uchun tayyorlanayotgan edik."},
      {"en": "It was raining when I left home.", "uz": "Men uyimdan chiqqanimda yomg‘ir yog‘ayotgan edi."},
      {"en": "He was driving too fast.", "uz": "U juda tez haydayotgan edi."},
      {"en": "The children were playing outside.", "uz": "Bolalar tashqarida o‘ynayotgan edi."},
      {"en": "I wasn’t listening to the teacher.", "uz": "Men o‘qituvchini tinglamayotgan edim."},
      {"en": "Were you sleeping when I texted?", "uz": "Men yozganimda uxlayotgan edingmi?"},
      {"en": "She was always complaining about something.", "uz": "U har doim nimadandir shikoyat qilardi."}
    ]
  },
  "Advanced Passive": {
    "rule_uz": "Advanced Passive — murakkab passiv shakllar, modal fe’llar yoki zamon kombinatsiyalari bilan ishlatiladi. Bu shakl e’tiborni bajaruvchidan emas, balki harakatga yoki natijaga qaratadi.",
    "structure": "S + be + V3 (+ by ...)",
    "examples": [
      {"en": "The report has been completed by the manager.", "uz": "Hisobot menejer tomonidan yakunlangan."},
      {"en": "The project will be finished next week.", "uz": "Loyiha keyingi haftada tugallanadi."},
      {"en": "The cake was made by my mother.", "uz": "Tort onam tomonidan tayyorlangan."},
      {"en": "The house had been built before 2000.", "uz": "Uy 2000-yilgacha qurilgan edi."},
      {"en": "The letter is being written.", "uz": "Xat yozilmoqda."},
      {"en": "English is spoken all over the world.", "uz": "Ingliz tili butun dunyoda so‘zlashiladi."},
      {"en": "He was sent to prison.", "uz": "U qamoqqa yuborilgan edi."},
      {"en": "This problem can be solved easily.", "uz": "Bu muammoni oson hal qilish mumkin."},
      {"en": "The results are not yet published.", "uz": "Natijalar hali e’lon qilinmagan."},
      {"en": "The car was repaired by a mechanic.", "uz": "Mashina mexanik tomonidan ta’mirlangan."}
    ]
  },
  "Reported Speech (advanced)": {
    "rule_uz": "Reported Speech (advanced) — bu boshqalarning so‘zlarini bilvosita (indirect) shaklda ifodalaydi. Fe’l zamoni bir pog‘ona orqaga suriladi, shuningdek zamonlar ketma-ketligi qoidasiga rioya qilinadi.",
    "structure": "S + said/told + (that) + S + V (past form)",
    "examples": [
      {"en": "He said that he was tired.", "uz": "U charchaganini aytdi."},
      {"en": "She told me that she had finished the work.", "uz": "U menga ishni tugatganini aytdi."},
      {"en": "They said they would come tomorrow.", "uz": "Ular ertaga kelishlarini aytishdi."},
      {"en": "I said I didn’t know the answer.", "uz": "Men javobni bilmasligimni aytdim."},
      {"en": "She said she could help me.", "uz": "U menga yordam bera olishini aytdi."},
      {"en": "He told us he had been waiting.", "uz": "U bizga kutayotganini aytdi."},
      {"en": "They said they were going to travel.", "uz": "Ular sayohatga chiqishayotganini aytishdi."},
      {"en": "She said that she hadn’t seen him.", "uz": "U uni ko‘rmaganini aytdi."},
      {"en": "He told me that he might call later.", "uz": "U menga keyinroq qo‘ng‘iroq qilishi mumkinligini aytdi."},
      {"en": "They said that it was raining.", "uz": "Ular yomg‘ir yog‘ayotganini aytishdi."}
    ]
  }
}
,
   "C1": {
  "Future Perfect": {
    "rule_uz": "Future Perfect zamoni kelajakda ma'lum bir vaqtgacha bajarilib bo‘ladigan ishlarni ifodalaydi. Bu zamon 'will have + V3' yordamida yasaladi. U ko‘pincha 'by the time', 'before', 'when' kabi vaqt bog‘lovchilari bilan ishlatiladi.",
    "structure": "Subject + will have + Past Participle (V3)",
    "examples": [
      { "en": "I will have finished my work by 6 o’clock.", "uz": "Men soat 6 gacha ishni tugatgan bo‘laman." },
      { "en": "She will have left before you arrive.", "uz": "Siz yetib kelishingizdan oldin u ketgan bo‘ladi." },
      { "en": "We will have eaten by then.", "uz": "O‘sha paytga kelib biz ovqatlanib bo‘lgan bo‘lamiz." },
      { "en": "They will have completed the project.", "uz": "Ular loyiha ustida ishni tugatgan bo‘lishadi." },
      { "en": "He will have read the book.", "uz": "U kitobni o‘qib chiqqan bo‘ladi." },
      { "en": "You will have visited London by next year.", "uz": "Keyingi yilgacha siz Londonni ziyorat qilgan bo‘lasiz." },
      { "en": "I will have learned English.", "uz": "Men ingliz tilini o‘rgangan bo‘laman." },
      { "en": "She will have cooked dinner.", "uz": "U kechki ovqatni tayyorlab bo‘ladi." },
      { "en": "We will have gone home.", "uz": "Biz uyga ketgan bo‘lamiz." },
      { "en": "He will have done his homework.", "uz": "U uy vazifasini bajargan bo‘ladi." }
    ]
  },

  "Future Continuous": {
    "rule_uz": "Future Continuous zamoni kelajakda ma'lum vaqt davomida davom etayotgan harakatni bildiradi. 'will be + V-ing' shaklida yasaladi.",
    "structure": "Subject + will be + Verb-ing",
    "examples": [
      { "en": "I will be studying at 8 o’clock.", "uz": "Soat 8 da men o‘qiyotgan bo‘laman." },
      { "en": "She will be sleeping when you arrive.", "uz": "Siz kelganingizda u uxlayotgan bo‘ladi." },
      { "en": "They will be working tomorrow morning.", "uz": "Ular ertaga ertalab ishlayotgan bo‘lishadi." },
      { "en": "We will be traveling next week.", "uz": "Biz keyingi haftada sayohatda bo‘lamiz." },
      { "en": "He will be watching TV in the evening.", "uz": "U kechqurun televizor ko‘rayotgan bo‘ladi." },
      { "en": "You will be reading this book soon.", "uz": "Tez orada siz bu kitobni o‘qiyotgan bo‘lasiz." },
      { "en": "I will be waiting for you.", "uz": "Men sizni kutayotgan bo‘laman." },
      { "en": "They will be eating dinner.", "uz": "Ular kechki ovqatni yeyotgan bo‘lishadi." },
      { "en": "She will be learning Spanish.", "uz": "U ispan tilini o‘rganayotgan bo‘ladi." },
      { "en": "We will be preparing for the test.", "uz": "Biz testga tayyorlanayotgan bo‘lamiz." }
    ]
  },

  "Advanced Conditionals": {
    "rule_uz": "Advanced Conditionals murakkab shart gaplarda ishlatiladi. Ular 'if' bilan birga turli zamon shakllarini o‘z ichiga oladi: Mixed, Inverted, va Unreal Conditionals.",
    "structure": "If + Past Perfect → would have + V3 / Mixed shakllar",
    "examples": [
      { "en": "If I had known, I would have helped you.", "uz": "Agar bilganimda, sizga yordam bergan bo‘lardim." },
      { "en": "If she were here, we would be happy.", "uz": "Agar u bu yerda bo‘lganida, biz baxtli bo‘lardik." },
      { "en": "If they studied harder, they would succeed.", "uz": "Agar ular ko‘proq o‘qishsa, muvaffaqiyatga erishishardi." },
      { "en": "If it rains, we will stay at home.", "uz": "Agar yomg‘ir yog‘sa, biz uyda qolamiz." },
      { "en": "Had I known the truth, I would not have gone.", "uz": "Haqiqatni bilganimda, bormagan bo‘lardim." },
      { "en": "If you were rich, you could buy a car.", "uz": "Agar siz boy bo‘lganingizda, mashina sotib olgan bo‘lardingiz." },
      { "en": "If he had worked harder, he would have passed.", "uz": "U ko‘proq ishlaganida, o‘tgan bo‘lardi." },
      { "en": "Were it not for you, I’d be lost.", "uz": "Siz bo‘lmaganingizda, men yo‘qolgan bo‘lardim." },
      { "en": "If I win, I’ll travel the world.", "uz": "Agar yutsam, dunyoni kezaman." },
      { "en": "If they had called, we would have met.", "uz": "Agar ular qo‘ng‘iroq qilganida, uchrashgan bo‘lardik." }
    ]
  }
}
   }
  
};
function getLevels(){ return AZ_DATA.levels; }
function getWords(level){ return AZ_DATA.words[level] || []; }
function getGrammar(level){ return AZ_DATA.grammar[level] || {}; }
